name: Fetch Google Sheet

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allows manual trigger

jobs:
  fetch_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python scripts/fetch_sheet.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sheet_data.csv
          git commit -m "Update CSV"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
